#!/bin/bash
vboxdrv="/lib/modules/$(uname -r)/misc/vboxdrv.ko"
vboxnetadp="/lib/modules/$(uname -r)/misc/vboxnetadp.ko"
vboxnetflt="/lib/modules/$(uname -r)/misc/vboxnetflt.ko"
if [ -f $vboxdrv ]; then
    rmmod $vboxnetadp && rmmod $vboxnetflt && rmmod $vboxdrv
    insmod $vboxdrv && insmod $vboxnetadp && insmod $vboxnetflt
else
    echo "Error: Unable to find $vboxdrv\nPlease run /sbin/vboxconfig and try again"
fi
